name: savessa
description: A community-based savings tracker app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6
  algorand_dart: ^2.0.0-dev.14
  fl_chart: ^0.65.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutterwave_standard: ^1.0.8
  postgres: ^2.6.3
  intl: ^0.20.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^13.2.0
  easy_localization: ^3.0.3
  feather_icons: ^1.2.0
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  page_transition: ^2.2.1
  confetti: ^0.7.0
  url_launcher: ^6.3.0
  local_auth: ^2.3.0
  otp: ^3.1.1
  qr_flutter: ^4.1.0
  mailer: ^6.1.0

  async: any
  intl_phone_field: ^3.2.0
  geolocator: ^14.0.2
  geocoding: ^2.1.1
  flutter_native_splash: ^2.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Assets configuration
flutter:
  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/icons/flags/
    - assets/icons/svg/
    - assets/sounds/
    - .env

flutter_native_splash:
  color: "#4B2E83" # fallback background (royal purple)
  image: assets/images/logo.png
  android_12:
    color: "#4B2E83"
    image: assets/images/logo.png
  web: false
