// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBDur2ZWqdrREM8Wi0Hsn6RYeoIBT6jgQ',
    appId: '1:878601589661:web:67b5ab03c7b278d2f79574',
    messagingSenderId: '878601589661',
    projectId: 'savessa-28ec0',
    authDomain: 'savessa-28ec0.firebaseapp.com',
    storageBucket: 'savessa-28ec0.firebasestorage.app',
    measurementId: 'G-G4TE2SRV9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_pPeG_2mFEMsXomb60vyfo_W88JmcEA',
    appId: '1:878601589661:android:334be7a408eafcc4f79574',
    messagingSenderId: '878601589661',
    projectId: 'savessa-28ec0',
    storageBucket: 'savessa-28ec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysvulJfieq6xzWvketbNoH5e94O5uTW0',
    appId: '1:878601589661:ios:8e7f7c48419b12e1f79574',
    messagingSenderId: '878601589661',
    projectId: 'savessa-28ec0',
    storageBucket: 'savessa-28ec0.firebasestorage.app',
    iosBundleId: 'com.example.savessa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBysvulJfieq6xzWvketbNoH5e94O5uTW0',
    appId: '1:878601589661:ios:8e7f7c48419b12e1f79574',
    messagingSenderId: '878601589661',
    projectId: 'savessa-28ec0',
    storageBucket: 'savessa-28ec0.firebasestorage.app',
    iosBundleId: 'com.example.savessa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBDur2ZWqdrREM8Wi0Hsn6RYeoIBT6jgQ',
    appId: '1:878601589661:web:63b9f8192496a3fdf79574',
    messagingSenderId: '878601589661',
    projectId: 'savessa-28ec0',
    authDomain: 'savessa-28ec0.firebaseapp.com',
    storageBucket: 'savessa-28ec0.firebasestorage.app',
    measurementId: 'G-VHSTC0DV06',
  );
}
